version: '3.1'

services:

 wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_password
      WORDPRESS_DB_NAME: wordpress

 db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: password
     volumes:
      - "~/Docker/mariadb/datadir:/var/lib/mysql"

